name: famibo
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter_simple_calculator: 
  flutter:
    sdk: flutter



 
  cupertino_icons: ^1.0.2
  glassmorphism: ^3.0.0
  html: ^0.15.4
  http: ^1.1.0
  animated_gesture_detector: ^1.0.0
  glassmorphism_buttons: ^0.0.8
  scrollable_clean_calendar: ^1.4.1
  cached_network_image: ^3.2.3
  animated_splash_screen: ^1.3.0
  google_sign_in: ^6.1.5
  onboarding: ^3.1.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
  fonts:
    - family: OriginalSurfer
      fonts:
        - asset: assets/fonts/OriginalSurfer-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
